### ISSUE TITLE
Add duikers, steenbok, and maybe bats, insects/spiders to SS GUI

### ISSUE THREAD

**Issue by mkosmala** [SnapshotSerengetiScienceTeam/DataManagement#17]
I'd love to see this happen, especially for duikers and steenbok. Right now those are getting classified *wrong*, whereas for insects/spiders they're just missed, which isn't so bad. Bats I don't have a good sense of... they might be getting classified as rodents or otherBirds, but haven't looked into it. If we do this when we launch S8, then we only have to do #9 for S1-S7.

**Comment by aliburchard** [comment]
@palme516 Can you 
1) write up the text for the "easily confused with" buttons for duiker/steenbok/dikdik? (if you play with the interface, you'll see where it's missing).
2) Was thinking we might also want to add "cattle" into the easily confused with wildebeest and buffalo. They are similarly shaped, and non-serengeti folks indicate they are wildly mistakable. I'd say focus on the hump and color. (are cattle ever dark brown? at least wildes and buffs are never patchy...)...

**Comment by palme516** [comment]
@aliburchard Does this work? 

#Duiker often confused with: 

Reedbuck: Reedbuck lack the dark muzzle and forelegs of a duiker. The horns of a male duiker are straighter and smoother than those of a male reedbuck. 

Dik dik: Dik dik are smaller and less stocky than a duiker, lacking the prominently dark muzzle and foreleg stripes.

Steenbok: Steenbok are more petite than duiker. The black facial glands of a steenbok do not extend to cover as much of the face as the dark muzzle stripe of the duiker. 

#Steenbok often confused with: 

Duiker: A duiker is larger than a steenbok, with a more prominent black facial stripe and dark forelimbs. 

Dik dik: Dik dik have a more rounded back and hunched posture than a steenbok. Dik dik have a more prominent tuft of hair between their ears. 

#Dik dik often confuse with (*need to add buttons): 

Steenbok: Steenbok have larger ears than dik dik and lack the dark suborbital gland. They are slightly bigger in size.  

Duiker: Dik dik have more petite, tapering noses that lack the dark muzzle stripe of a duiker. Dik dik have more prominent tufts of hair between their ears and a rounded posture. 

#Cattle often confused with (*need to add buttons): 

Buffalo: Buffalo are stockier than cattle and lack the prominent shoulder hump. The horns of cattle don't join together in the middle.  

Wildebeest: The horns of cattle are shorter and don't extend as far back as those of wildebeest. While cattle have a prominent should hump, they don't have the sloping back of wildebeest and lack a chin-beard. 

#Wildebeest often confused with (*need to add button): 

Cattle: Wildebeest have more pronounced, curving horns than cattle. Cattle have a less bulbous muzzle and they lack the wildebeest's chin-beard. 

#Buffalo often confused with (*need to add button): 

Cattle: Cattle are less heavy than buffalo, and have a more pronounced should hump. The horns of cattle don't fuse in the middle and cattle are often more variable in color.

**Comment by aliburchard** [comment]
@palme516 @mkosmala looks good to me!

**Comment by mkosmala** [comment]
"should" should be "shoulder"

**Comment by mkosmala** [comment]
@aliburchard @palme516 Probably too late, but I just was rereading old blog posts and saw that we have seen a pangolin in the captures. Maybe better to have 'pangolin' than 'vulture'. But perhaps it's too late for Season 8. Thoughts?

**Comment by aliburchard** [comment]
We've only seen a pangolin once in three years of images -- I think vultures are a better option (and one that could be useful for anyone studying scavenging behavior).

**Comment by mkosmala** [comment]
Duikers and steenboks and zorillas and such are rare, too. The issue is that there's no correct category if you *do* see a pangolin. There *is* another correct option (otherBird) if you see a vulture and we don't have a category for it.

**Comment by aliburchard** [comment]
I don't think we really need a zorilla option either, to be honest, unless we had a scientist actively studying zorillas. Things that are that rare are easily found by hashtagging, and spark a fair bit of conversation with a "what is this?" thread. We don't have crocodiles or tortoises, and both of those are in our study area and more common than pangolins -- I would have thought we'd see one of them long before a pangolin on the cameras (Craig has been in the Serengeti for how many years and had never seen one (until Daniel did, and suddenly Craig had a story of having seen a pangolin once)). 

There's simply no way to include an option for every single species that might be seen in the cameras, and I highly doubt we will ever see a pangolin on camera again. I think duikers and steenboks are fine to include because they've appeared much more often than we expected (>5 times each) and likely get classified as dik diks or impala or reedbuck or gazelles without us realising it.

**Comment by mkosmala** [comment]
Understood. But we don't actually know if we're missing rare things that *don't* get tagged on Talk. We only see the ones that do. Getting tagged on Talk requires being seen by at least one person who bothers to use Talk. And we know that the vast majority of users don't use Talk.

**Comment by aliburchard** [comment]
True. Do we have any idea what percent of users do use talk?

On the upside, at least 10 people will see every image (and because of the rate of processing, we get an average of nearly 50 people per image, it seems). But that's a good point.

**Comment by mkosmala** [comment]
No, actually an analysis of how many users (and which users -- are they the ones that contribute most of the classifications?) would be really interesting.

Yes, agreed, that I think we catch a lot. But I've also come across images that I'm really surprised haven't been tagged in Talk. Anyway, I think it's too late for pangolin this time around. But maybe keep 'em in mind for the future...
