### ISSUE TITLE
Give up DreamHost?

### ISSUE THREAD

**Issue by mkosmala** [SnapshotSerengetiScienceTeam/DataManagement#36]
@aliburchard, @palme516 and I were discussing whether we need DreamHost anymore. Now that we've got 18 TB at MSI, can we move anything we still need or want to keep to MSI and shut down our DreamHost account?

**Comment by aliburchard** [comment]
Definitely. I'm not sure there is anything at Dreamhost anymore, actually, that's not at MSI. Have we confirmed that the fullest-res photos are all at MSI?

**Comment by mkosmala** [comment]
I'm pretty sure that only full-res photos are at MSI. When I copied S1-3 from Dreamhost, I didn't reduce images. And I've never loaded images from Zooniverse to MSI. Any other reason to think we might have non-full-res images at MSI?

**Comment by aliburchard** [comment]
We had various reduced size images at Dreamhost for displaying on the Serengeti Live website, but they were labeled in folders as medium and small. So unless you used those (I can't imagine why), then we should be good.

**Comment by mkosmala** [comment]
Great, then let's ditch it. Craig will be thrilled. @palme516, can you look into how to close out our account at DreamHost?

**Comment by palme516** [comment]
Yup! I'll let Craig know and shut it down.

**Comment by palme516** [comment]
Ugh, wait, it looks like lionresearch.org is also linked with DreamHost? But the hosting is DNS only (my (poor) understanding of this is that DreamHost simply routes domain names to the website...). I can't find any data on DreamHost that might be linked with lionresearch.org. I assume there are other, cheaper DNS services we could use?

**Comment by aliburchard** [comment]
Hm. There is no data on DreamHost that has anything to do with the
lionresearch.org site. And lionresearch.org redirects to the UMN hosted
site anyway. So we jsut have to keep that domain name, and I assume there
are cheaper options -- might be best to ask the folks who maintain the
lionresearch website (they're in CBS. Not IT, but Steph Xenos or....Craig
might remember the name of the office....)

On Thu, Jan 15, 2015 at 2:13 PM, palme516 <notifications@github.com> wrote:

> Ugh, wait, it looks like lionresearch.org is also linked with DreamHost?
> But the hosting is DNS only (my (poor) understanding of this is that
> DreamHost simply routes domain names to the website...). I can't find any
> data on DreamHost that might be linked with lionresearch.org. I assume
> there are other, cheaper DNS services we could use?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SnapshotSerengetiScienceTeam/DataManagement/issues/36#issuecomment-70090471>
> .
>



-- 
Alexandra Swanson, Ph.D.
Ecology & Citizen Science Postdoc
The Zooniverse
University of Oxford

**Comment by palme516** [comment]
Okay, I'll email Craig and get in touch with these people
