### ISSUE TITLE
Update cleaning script output format

### ISSUE THREAD

**Issue by mkosmala** [SnapshotSerengetiScienceTeam/DataManagement#49]
Forked from #4:
The cleaning scripts should produce a format that looks like the following:
COLUMNS:
season: integer (season number)
site: 3-character alphanumeric representing gridcell of the camera
roll: integer (roll number within site)
capture: integer (capture number within roll)
image: integer (image number within capture)
path: full path and file name of image
newtime: corrected datetime for the image (format YYYY-MM-DD HH:MM:SS)
oldtime: original JPG datetime for the image (format YYYY-MM-DD HH:MM:SS)
invalid: integer (invalid code)
include: 1 if the image should be sent to Zooniverse, 0 if not

**Comment by palme516** [comment]
Done. Will upload new scripts to GitHub and MSI later tonight.

**Comment by palme516** [comment]
Scripts are up on both.

**Comment by mkosmala** [comment]
Looks pretty good. Note that the format is not exactly as I have it above. But I can work with it. Actual format output of scripts is:

COLUMNS:
[no name]: row number (integer increasing)
season: integer (season number)
site: 3-character alphanumeric representing gridcell of the camera
roll: integer (roll number within site)
capture: integer (capture number within roll)
image: integer (image number within capture)
path: full path and file name of image
newtime: corrected datetime for the image (format YYYY-MM-DD HH:MM:SS)
oldtime: original JPG datetime for the image (format YYYY:MM:DD HH:MM:SS)
invalid: integer (invalid code)
include: 1 if the image should be sent to Zooniverse, 0 if not
