### ISSUE TITLE
Document data import and cleaning processes

### ISSUE THREAD

**Issue by mkosmala** [SnapshotSerengetiScienceTeam/DataManagement#56]
Write instructions on how to get images off of hard drives and onto MSI.
Then write instructions on how to go through the data cleaning steps so that everything is ready for (1) import into the database; and (2) export to Zooniverse.

These docs may already exist, but should live here on GitHub. @palme516 ?

**Comment by palme516** [comment]
Just committed to the "How-To" directory

**Comment by palme516** [comment]
Should be there now, let me know if you still can't get to it!
