### ISSUE TITLE
Zooniverse importing invalid captures

### ISSUE THREAD

**Issue by mkosmala** [SnapshotSerengetiScienceTeam/DataManagement#64]
This issue is a spin-off from #55:

@aliburchard For S7, Zooniverse appears to have grabbed all captures, including those marked invalid=1 and send-to-Zooniverse=0. Can you double-check that the import scripts are properly ignoring invalid images?

**Comment by aliburchard** [comment]
Yeah, this was a mistake. Not sure if S8 included these, but we definitely fixed this for S9.
