### ISSUE TITLE
Revamp scripts in light of Zooniverse retirement recording change

### ISSUE THREAD

**Issue by mkosmala** [SnapshotSerengetiScienceTeam/DataManagement#65]
Related to #55. Previously, when we got a data dump from Zooniverse, the retirement reason was the same for all classifications for a given capture. (For example, 'consensus'.) But for S7 and S8, the dump from Zooniverse has 'none' as the retirement reason for early classifications and only becomes a valid retirement reason when the capture retires. So, for example, the first 13 classifications for a capture might be 'none', but the 14th might be 'consensus'. 

This is annoying because the current plurality consensus script uses the retirement reason from the FIRST classification for a capture. We will need to change it so it pulls the retirement reason from the LAST classification for a capture.

**Comment by mkosmala** [comment]
The script that needs modification is /home/packerc/shared/classifications_data/scripts/plurality_consensus.py.

_Cory edit: /home/packerc/shared/scripts/plurality_consensus.py._

**Comment by tesherista** [comment]
Fixed.
