### ISSUE TITLE
Add new S7 species to database

### ISSUE THREAD

**Issue by mkosmala** [SnapshotSerengetiScienceTeam/DataManagement#66]
Related to #55: For S7, we added six new "species" to Snapshot Serengeti that users could choose from. These now need to be added to the database in table 'Species'. @tesherista, you should be able to do this quite easily. `idSpecies` auto-increments. The species values to add are:
`duiker`, `steenbok`, `cattle`, `bat`, `insectSpider`, `vulture`

After you've done that, you'll also need to update this script:
/home/packerc/shared/metadata_db/scripts/transform-ZooniverseClassifications.py 
by adding the six species and their database IDs to the species dictionary. 

Please let me know when these things are done. Thanks!

**Comment by tesherista** [comment]
Took a while just because I was having such a hard time getting MSI to let me connect to the db; all the new species are now in both the species table & the script.
